-- Release 3: Pedidos, Caja y Taller simplificado.
-- Migración aditiva: no elimina ni modifica datos históricos de clientes o citas.

create type public.production_route as enum (
  'stock_adjustments',
  'existing_design',
  'new_design'
);

create type public.order_status as enum (
  'quote',
  'confirmed',
  'pending_planning',
  'planned',
  'in_production',
  'pending_fitting_1',
  'corrections',
  'pending_fitting_2',
  'finishing',
  'ready',
  'delivered',
  'closed',
  'on_hold',
  'cancelled'
);

create type public.cost_phase as enum ('estimated', 'actual');
create type public.cost_category as enum ('fabric', 'lining', 'accessories', 'external_service', 'other');
create type public.payment_method as enum ('cash', 'transfer', 'debit_card', 'credit_card', 'other');
create type public.cash_direction as enum ('income', 'expense');
create type public.ledger_status as enum ('posted', 'reversed');

insert into public.app_settings(setting_key, setting_value, description) values
  ('workshop_default_weekly_hours', '40'::jsonb, 'Horas productivas disponibles por semana en el taller'),
  ('workshop_hourly_cost', '0'::jsonb, 'Costo interno por hora de taller en CLP'),
  ('workshop_capacity_warning_percent', '85'::jsonb, 'Porcentaje semanal que activa advertencia de capacidad'),
  ('default_tax_rate', '19'::jsonb, 'IVA predeterminado para nuevos pedidos'),
  ('default_sales_commission_rate', '0'::jsonb, 'Comisión de venta predeterminada para nuevos pedidos'),
  ('default_card_fee_rate', '0'::jsonb, 'Comisión Transbank predeterminada para nuevos pedidos')
on conflict (setting_key) do nothing;

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_sequence bigint generated by default as identity unique,
  client_id uuid not null references public.clients(id),
  source_appointment_id uuid references public.appointments(id) on delete set null,
  seller_id uuid references public.profiles(id) on delete set null,
  production_route public.production_route not null,
  status public.order_status not null default 'quote',
  product_name text not null,
  design_description text,
  sale_date date,
  event_date date,
  promised_delivery_date date,
  production_start_date date,
  planned_week_start date,
  actual_delivery_date date,
  planned_hours numeric(9,2) check (planned_hours is null or planned_hours >= 0),
  actual_hours numeric(9,2) check (actual_hours is null or actual_hours >= 0),
  variance_reason text,
  needs_fitting_1 boolean not null default true,
  needs_fitting_2 boolean not null default true,
  internal_notes text,
  created_by uuid not null default auth.uid() references public.profiles(id),
  updated_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_delivery_dates check (
    actual_delivery_date is null
    or promised_delivery_date is null
    or actual_delivery_date >= sale_date
  ),
  constraint orders_variance_reason check (
    actual_hours is null
    or planned_hours is null
    or actual_hours = planned_hours
    or nullif(trim(variance_reason), '') is not null
  )
);

create index orders_client_idx on public.orders(client_id, created_at desc);
create index orders_workshop_idx on public.orders(status, planned_week_start, promised_delivery_date)
  where status not in ('closed', 'cancelled');
create index orders_source_appointment_idx on public.orders(source_appointment_id)
  where source_appointment_id is not null;

create table public.order_financials (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  gross_sale_amount numeric(14,2) not null default 0 check (gross_sale_amount >= 0),
  discount_amount numeric(14,2) not null default 0 check (discount_amount >= 0),
  tax_rate_snapshot numeric(7,4) not null default 19 check (tax_rate_snapshot between 0 and 100),
  sales_commission_rate_snapshot numeric(7,4) not null default 0 check (sales_commission_rate_snapshot between 0 and 100),
  card_fee_rate_snapshot numeric(7,4) not null default 0 check (card_fee_rate_snapshot between 0 and 100),
  workshop_hourly_cost_snapshot numeric(14,2) not null default 0 check (workshop_hourly_cost_snapshot >= 0),
  created_by uuid not null default auth.uid() references public.profiles(id),
  updated_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_financial_discount check (discount_amount <= gross_sale_amount)
);

create table public.order_cost_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  phase public.cost_phase not null,
  category public.cost_category not null,
  description text not null,
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit text not null default 'unidad',
  unit_cost numeric(14,2) not null default 0 check (unit_cost >= 0),
  total_cost numeric(14,2) generated always as (round(quantity * unit_cost, 2)) stored,
  created_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now()
);
create index order_cost_items_order_idx on public.order_cost_items(order_id, phase, category);

create table public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id),
  amount numeric(14,2) not null check (amount <> 0),
  method public.payment_method not null,
  paid_at timestamptz not null default now(),
  reference text,
  document_number text,
  card_fee_rate_snapshot numeric(7,4) not null default 0 check (card_fee_rate_snapshot between 0 and 100),
  status public.ledger_status not null default 'posted',
  reversal_of uuid references public.order_payments(id),
  notes text,
  created_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint order_payment_reversal check (
    (status = 'posted' and reversal_of is null)
    or (status = 'reversed' and reversal_of is not null)
  )
);
create index order_payments_order_idx on public.order_payments(order_id, paid_at desc);
create unique index order_payment_single_reversal_idx on public.order_payments(reversal_of)
  where reversal_of is not null;

create table public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete set null,
  direction public.cash_direction not null,
  category text not null,
  amount numeric(14,2) not null check (amount > 0),
  method public.payment_method not null,
  occurred_at timestamptz not null default now(),
  description text not null,
  reference text,
  status public.ledger_status not null default 'posted',
  reversal_of uuid references public.cash_movements(id),
  created_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint cash_movement_reversal check (
    (status = 'posted' and reversal_of is null)
    or (status = 'reversed' and reversal_of is not null)
  )
);
create index cash_movements_date_idx on public.cash_movements(occurred_at desc);
create unique index cash_movement_single_reversal_idx on public.cash_movements(reversal_of)
  where reversal_of is not null;

create table public.workshop_capacity_exceptions (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  available_hours numeric(9,2) not null check (available_hours >= 0),
  reason text,
  created_by uuid not null default auth.uid() references public.profiles(id),
  updated_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workshop_capacity_monday check (extract(isodow from week_start) = 1)
);

alter table public.appointments
  add column order_id uuid references public.orders(id) on delete set null;
create index appointments_order_idx on public.appointments(order_id)
  where order_id is not null;

create trigger orders_updated_at before update on public.orders
  for each row execute function public.set_updated_at();
create trigger order_financials_updated_at before update on public.order_financials
  for each row execute function public.set_updated_at();
create trigger workshop_capacity_updated_at before update on public.workshop_capacity_exceptions
  for each row execute function public.set_updated_at();

create trigger audit_orders after insert or update or delete on public.orders
  for each row execute function public.audit_row_change();
create trigger audit_order_financials after insert or update or delete on public.order_financials
  for each row execute function public.audit_row_change();
create trigger audit_order_cost_items after insert or update or delete on public.order_cost_items
  for each row execute function public.audit_row_change();
create trigger audit_order_payments after insert or update or delete on public.order_payments
  for each row execute function public.audit_row_change();
create trigger audit_cash_movements after insert or update or delete on public.cash_movements
  for each row execute function public.audit_row_change();
create trigger audit_workshop_capacity after insert or update or delete on public.workshop_capacity_exceptions
  for each row execute function public.audit_row_change();

create or replace function public.can_manage_commercial()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role()::text in ('admin', 'seller'), false);
$$;

create or replace function public.can_manage_workshop()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role()::text in ('admin', 'workshop'), false);
$$;

create or replace function public.create_order_with_financials(
  p_client_id uuid,
  p_source_appointment_id uuid,
  p_production_route public.production_route,
  p_product_name text,
  p_design_description text,
  p_sale_date date,
  p_event_date date,
  p_promised_delivery_date date,
  p_gross_sale_amount numeric,
  p_discount_amount numeric,
  p_internal_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_tax numeric := coalesce((select (setting_value #>> '{}')::numeric from public.app_settings where setting_key = 'default_tax_rate'), 19);
  v_commission numeric := coalesce((select (setting_value #>> '{}')::numeric from public.app_settings where setting_key = 'default_sales_commission_rate'), 0);
  v_card_fee numeric := coalesce((select (setting_value #>> '{}')::numeric from public.app_settings where setting_key = 'default_card_fee_rate'), 0);
  v_hour_cost numeric := coalesce((select (setting_value #>> '{}')::numeric from public.app_settings where setting_key = 'workshop_hourly_cost'), 0);
begin
  if not public.can_manage_commercial() then
    raise exception 'Usuario no autorizado para crear pedidos';
  end if;
  if nullif(trim(p_product_name), '') is null then
    raise exception 'El producto o vestido es obligatorio';
  end if;
  if p_gross_sale_amount < 0 or p_discount_amount < 0 or p_discount_amount > p_gross_sale_amount then
    raise exception 'Los montos comerciales no son válidos';
  end if;
  if p_source_appointment_id is not null and not exists (
    select 1 from public.appointments
    where id = p_source_appointment_id and client_id = p_client_id
  ) then
    raise exception 'La cita de origen debe pertenecer a la misma cliente';
  end if;

  insert into public.orders(
    client_id, source_appointment_id, seller_id, production_route, status,
    product_name, design_description, sale_date, event_date,
    promised_delivery_date, internal_notes, created_by, updated_by
  ) values (
    p_client_id, p_source_appointment_id, auth.uid(), p_production_route, 'pending_planning',
    trim(p_product_name), nullif(trim(p_design_description), ''), p_sale_date,
    p_event_date, p_promised_delivery_date, nullif(trim(p_internal_notes), ''),
    auth.uid(), auth.uid()
  ) returning id into v_order_id;

  insert into public.order_financials(
    order_id, gross_sale_amount, discount_amount, tax_rate_snapshot,
    sales_commission_rate_snapshot, card_fee_rate_snapshot,
    workshop_hourly_cost_snapshot, created_by, updated_by
  ) values (
    v_order_id, p_gross_sale_amount, p_discount_amount, v_tax,
    v_commission, v_card_fee, v_hour_cost, auth.uid(), auth.uid()
  );

  if p_source_appointment_id is not null then
    update public.appointments
       set order_id = v_order_id, updated_by = auth.uid(), updated_at = now()
     where id = p_source_appointment_id;
  end if;

  return v_order_id;
end;
$$;

create or replace function public.reverse_order_payment(p_payment_id uuid, p_reason text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.order_payments%rowtype;
  v_reversal_id uuid;
begin
  if not public.can_manage_commercial() then raise exception 'Usuario no autorizado'; end if;
  if nullif(trim(p_reason), '') is null then raise exception 'El motivo es obligatorio'; end if;

  select * into v_payment from public.order_payments
  where id = p_payment_id and status = 'posted' for update;
  if not found then raise exception 'Pago no encontrado o ya reversado'; end if;

  insert into public.order_payments(
    order_id, amount, method, paid_at, reference, document_number,
    card_fee_rate_snapshot, status, reversal_of, notes, created_by
  ) values (
    v_payment.order_id, -v_payment.amount, v_payment.method, now(),
    v_payment.reference, v_payment.document_number, v_payment.card_fee_rate_snapshot,
    'reversed', v_payment.id, trim(p_reason), auth.uid()
  ) returning id into v_reversal_id;

  return v_reversal_id;
end;
$$;

create or replace function public.link_appointment_to_order(p_appointment_id uuid, p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_client uuid;
  v_appointment_client uuid;
begin
  if not public.is_internal_user() then raise exception 'Usuario no autorizado'; end if;
  select client_id into v_order_client from public.orders where id = p_order_id;
  select client_id into v_appointment_client from public.appointments where id = p_appointment_id;
  if v_order_client is null or v_appointment_client is null then
    raise exception 'Pedido o cita no encontrado';
  end if;
  if v_order_client <> v_appointment_client then
    raise exception 'La cita y el pedido deben pertenecer a la misma cliente';
  end if;
  update public.appointments
     set order_id = p_order_id, updated_by = auth.uid(), updated_at = now()
   where id = p_appointment_id;
end;
$$;

create or replace function public.reverse_cash_movement(p_movement_id uuid, p_reason text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_movement public.cash_movements%rowtype;
  v_reversal_id uuid;
begin
  if not public.can_manage_commercial() then raise exception 'Usuario no autorizado'; end if;
  if nullif(trim(p_reason), '') is null then raise exception 'El motivo es obligatorio'; end if;

  select * into v_movement from public.cash_movements
  where id = p_movement_id and status = 'posted' for update;
  if not found then raise exception 'Movimiento no encontrado o ya reversado'; end if;

  insert into public.cash_movements(
    order_id, direction, category, amount, method, occurred_at,
    description, reference, status, reversal_of, created_by
  ) values (
    v_movement.order_id,
    case when v_movement.direction = 'income' then 'expense'::public.cash_direction else 'income'::public.cash_direction end,
    'reverso', v_movement.amount, v_movement.method, now(),
    'Reverso: ' || trim(p_reason), v_movement.reference,
    'reversed', v_movement.id, auth.uid()
  ) returning id into v_reversal_id;

  return v_reversal_id;
end;
$$;

create or replace view public.order_financial_summary
with (security_invoker = true)
as
select
  o.id as order_id,
  o.order_sequence,
  f.gross_sale_amount,
  f.discount_amount,
  greatest(f.gross_sale_amount - f.discount_amount, 0) as final_sale_amount,
  case
    when f.tax_rate_snapshot = 0 then greatest(f.gross_sale_amount - f.discount_amount, 0)
    else greatest(f.gross_sale_amount - f.discount_amount, 0) / (1 + f.tax_rate_snapshot / 100)
  end as net_sales_amount,
  greatest(f.gross_sale_amount - f.discount_amount, 0)
    - case
        when f.tax_rate_snapshot = 0 then greatest(f.gross_sale_amount - f.discount_amount, 0)
        else greatest(f.gross_sale_amount - f.discount_amount, 0) / (1 + f.tax_rate_snapshot / 100)
      end as tax_amount,
  coalesce(sum(ci.total_cost) filter (where ci.phase = 'estimated'), 0) as estimated_material_cost,
  coalesce(sum(ci.total_cost) filter (where ci.phase = 'actual'), 0) as actual_material_cost,
  coalesce(o.planned_hours, 0) * f.workshop_hourly_cost_snapshot as estimated_labor_cost,
  coalesce(o.actual_hours, 0) * f.workshop_hourly_cost_snapshot as actual_labor_cost,
  greatest(f.gross_sale_amount - f.discount_amount, 0) * f.sales_commission_rate_snapshot / 100 as sales_commission,
  coalesce((
    select sum(abs(p.amount) * p.card_fee_rate_snapshot / 100)
    from public.order_payments p
    where p.order_id = o.id
      and p.status = 'posted'
      and p.amount > 0
      and p.method in ('debit_card', 'credit_card')
  ), 0) as card_fees,
  coalesce((select sum(p.amount) from public.order_payments p where p.order_id = o.id), 0) as paid_amount
from public.orders o
join public.order_financials f on f.order_id = o.id
left join public.order_cost_items ci on ci.order_id = o.id
group by o.id, o.order_sequence, f.order_id, f.gross_sale_amount, f.discount_amount,
  f.workshop_hourly_cost_snapshot, f.sales_commission_rate_snapshot;

alter table public.orders enable row level security;
alter table public.order_financials enable row level security;
alter table public.order_cost_items enable row level security;
alter table public.order_payments enable row level security;
alter table public.cash_movements enable row level security;
alter table public.workshop_capacity_exceptions enable row level security;

create policy orders_select_internal on public.orders for select to authenticated
  using (public.is_internal_user());
create policy orders_insert_commercial on public.orders for insert to authenticated
  with check (public.can_manage_commercial() and created_by = auth.uid());
create policy orders_update_operational on public.orders for update to authenticated
  using (public.can_manage_commercial() or public.can_manage_workshop())
  with check (public.can_manage_commercial() or public.can_manage_workshop());

create policy order_financials_select_commercial on public.order_financials for select to authenticated
  using (public.can_manage_commercial());
create policy order_financials_insert_commercial on public.order_financials for insert to authenticated
  with check (public.can_manage_commercial());
create policy order_financials_update_commercial on public.order_financials for update to authenticated
  using (public.can_manage_commercial()) with check (public.can_manage_commercial());

create policy order_cost_items_select_operations on public.order_cost_items for select to authenticated
  using (public.can_manage_commercial() or public.can_manage_workshop());
create policy order_cost_items_insert_operations on public.order_cost_items for insert to authenticated
  with check (public.can_manage_commercial() or public.can_manage_workshop());
create policy order_cost_items_update_operations on public.order_cost_items for update to authenticated
  using (public.can_manage_commercial() or public.can_manage_workshop())
  with check (public.can_manage_commercial() or public.can_manage_workshop());
create policy order_cost_items_delete_operations on public.order_cost_items for delete to authenticated
  using (public.can_manage_commercial() or public.can_manage_workshop());

create policy order_payments_select_commercial on public.order_payments for select to authenticated
  using (public.can_manage_commercial());
create policy order_payments_insert_commercial on public.order_payments for insert to authenticated
  with check (public.can_manage_commercial() and created_by = auth.uid());

create policy cash_movements_select_commercial on public.cash_movements for select to authenticated
  using (public.can_manage_commercial());
create policy cash_movements_insert_commercial on public.cash_movements for insert to authenticated
  with check (public.can_manage_commercial() and created_by = auth.uid());

create policy workshop_capacity_select_internal on public.workshop_capacity_exceptions for select to authenticated
  using (public.is_internal_user());
create policy workshop_capacity_manage on public.workshop_capacity_exceptions for all to authenticated
  using (public.can_manage_workshop()) with check (public.can_manage_workshop());

revoke all on function public.can_manage_commercial() from public, anon, authenticated;
revoke all on function public.can_manage_workshop() from public, anon, authenticated;
revoke all on function public.create_order_with_financials(uuid,uuid,public.production_route,text,text,date,date,date,numeric,numeric,text) from public, anon, authenticated;
revoke all on function public.reverse_order_payment(uuid,text) from public, anon, authenticated;
revoke all on function public.link_appointment_to_order(uuid,uuid) from public, anon, authenticated;
revoke all on function public.reverse_cash_movement(uuid,text) from public, anon, authenticated;

grant execute on function public.can_manage_commercial() to authenticated;
grant execute on function public.can_manage_workshop() to authenticated;
grant execute on function public.create_order_with_financials(uuid,uuid,public.production_route,text,text,date,date,date,numeric,numeric,text) to authenticated;
grant execute on function public.reverse_order_payment(uuid,text) to authenticated;
grant execute on function public.link_appointment_to_order(uuid,uuid) to authenticated;
grant execute on function public.reverse_cash_movement(uuid,text) to authenticated;

revoke all on table public.orders, public.order_financials, public.order_cost_items,
  public.order_payments, public.cash_movements, public.workshop_capacity_exceptions
  from anon;
revoke all on table public.order_financial_summary from anon;
revoke all on sequence public.orders_order_sequence_seq from anon;

grant select on public.orders, public.order_financials, public.order_cost_items,
  public.order_payments, public.cash_movements, public.workshop_capacity_exceptions,
  public.order_financial_summary to authenticated;
grant insert, update on public.orders, public.order_financials to authenticated;
grant insert, update, delete on public.order_cost_items, public.workshop_capacity_exceptions to authenticated;
grant insert on public.order_payments, public.cash_movements to authenticated;
grant usage, select on sequence public.orders_order_sequence_seq to authenticated;
